.TH PWD 1 "2026-05-15" "User Commands" "CLI-Improved Manual"
.SH NAME
pwd \- print name of current/working directory (smart-link version)
.SH SYNOPSIS
.B pwd
[\fIOPTION\fR]...
.SH DESCRIPTION
Print the full filename of the current working directory. 
.PP
This version is a "reduced-friction" wrapper designed to identify symbolic link 
paths. If the logical path (where you think you are) differs from the physical 
path (where the disk says you are), it displays both joined by an arrow.
.SH THE SCRIPT
This manual entry documents the following intercept script:
.IP
.nf
#!/bin/bash
DASHLPATH=$(pwd -L)
DASHPPATH=$(pwd -P)
if [[ $DASHLPATH != $DASHPPATH ]]; then 
  echo $DASHLPATH "=>" $DASHPPATH
else
  /bin/pwd
fi
.fi
.SH INSTALLATION
To replace the system default with this smart version, add the following 
to your \fB.bashrc\fR or \fB.functions\fR file:
.IP
\fBalias pwd='/path/to/your/script/pwd'\fR
.SH NOTES
If no symbolic link is detected, the script transparently executes the 
standard system \fB/bin/pwd\fR.
.SH AUTHOR
William Orian Wear (Bill Wear)
