.TH XDATE 1 "2026-05-15" "User Commands" "CLI-Improved Manual"
.SH NAME
xdate \- print a long date string to stdout.
.SH SYNOPSIS
.B xdate
[\fIOPTION\fR]...
.SH DESCRIPTION
\fBxdate\fR prints a long date string that includes the normal date output, the epoch number, and information about the days of the year. For example:
.PP
Sat May 16 13:04:20 CDT 2026, 1778954660; Day 136 of 365; 229 days remain.
.SH THE SCRIPT
This manual entry documents the following shellscript:
.IP
.nf
#!/bin/zsh
y=$(date +%Y) 
d=$(date +%-j) 
t=$(( (y % 4 == 0 && y % 100 != 0) || y % 400 == 0 ? 366 : 365 )) 
echo "$(date '+%a %b %d %H:%M:%S %Z %Y, %s'); Day $d of $t; $((t - d)) days remain."
.fi
.SH INSTALLATION
Copy the script from the GitHub repository to your personal executable directory.
.SH AUTHOR
William Orian Wear (Bill Wear)
